version: '3.5'

services: 
  php:
    #image: php:fpm
    environment: 
      - APACHE_RUN_USER=#1000
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:80
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw 
      MYSQL_DATABASE: tutorial
      MYSQL_USER: tutorial
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev 
    volumes:
      - ./mysqldata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql  
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST= db
      - PMA_PORT= 3306
volumes:
  mysqldata: {}
