version: "3.9"

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/src
    # environment:
    #   PYTHONUNBUFFERED: 1
    #   FLASK_ENV: development