insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 178);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 86);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'S', 76);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'M', 189);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 162);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'S', 154);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 144);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 213);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 16);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 87);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'M', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'M', 152);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 0);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 57);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 167);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 131);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 168);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 0);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 8);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 91);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 189);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 98);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'S', 193);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'S', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 177);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'S', 33);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 121);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 144);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 168);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 22);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 151);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 125);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 163);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 129);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 133);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 40);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'S', 16);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'M', 117);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'S', 168);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 152);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 138);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 68);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 86);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 206);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'M', 158);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 60);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 137);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 44);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 14);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'M', 88);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 118);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 169);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 144);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 128);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 45);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 134);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 73);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 197);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 66);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 64);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 26);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 84);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 173);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 57);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 160);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 148);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 102);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 94);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 94);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'M', 121);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'S', 90);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 153);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 117);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 43);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 131);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 186);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'M', 178);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 179);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 138);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 133);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'M', 123);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'S', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'M', 192);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 141);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 185);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 39);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 197);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 160);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 155);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 92);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'M', 107);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 24);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 119);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'S', 59);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'M', 99);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'M', 89);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 48);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 60);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 28);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'S', 34);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'S', 192);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 144);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'S', 169);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 46);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'S', 105);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 27);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'M', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 5);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 147);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 104);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 142);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 110);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 194);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 123);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 131);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'M', 200);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'M', 76);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 89);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 109);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'S', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 197);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 184);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 137);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 111);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 82);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 41);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 109);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 193);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 4);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 35);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 188);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 179);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 197);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 185);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 118);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 23);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'M', 20);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 184);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 93);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 209);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 45);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 25);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 115);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 94);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 16);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'M', 76);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 171);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 193);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 131);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 20);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 2);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'S', 211);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 47);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 151);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 169);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'M', 155);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'M', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 66);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 40);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'M', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 119);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 5);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'M', 11);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 176);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'S', 108);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'M', 141);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 49);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 195);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 90);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 169);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 9);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 201);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 55);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 113);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 41);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 177);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'S', 22);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'S', 206);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 54);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 174);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 150);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 59);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 120);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'M', 136);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 70);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 197);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 152);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 51);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 22);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 156);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 191);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 111);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 83);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 73);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'M', 136);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 68);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'S', 16);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 55);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 159);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 137);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 56);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 166);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 106);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 65);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 168);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 208);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'S', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'M', 19);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 94);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 204);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 161);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 211);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 185);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 199);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 161);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 160);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 149);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 98);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'M', 134);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 10);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 183);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 199);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 79);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'S', 86);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 194);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'S', 67);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 35);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 117);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 74);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'S', 129);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 198);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'M', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'M', 51);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 105);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'M', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 184);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 113);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 117);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 1);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 190);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 175);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'M', 35);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 81);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 149);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 40);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 138);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 180);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 124);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 125);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 175);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 60);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 46);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'S', 53);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 135);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 2);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 31);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 71);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 32);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 148);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 139);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 136);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 162);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 174);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 72);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 87);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'M', 70);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 115);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'S', 208);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 106);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 188);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 21);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 98);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 162);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 159);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 125);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 64);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 125);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'M', 168);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 154);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 21);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 109);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 50);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 115);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 142);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 64);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'M', 52);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'M', 118);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 196);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 178);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'S', 103);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 47);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 213);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 177);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 139);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'M', 167);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 47);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 211);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'S', 195);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'S', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 18);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 190);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 193);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 135);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 109);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 195);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 132);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 105);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 66);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'M', 40);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'M', 115);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'S', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 159);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 25);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 50);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 128);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 143);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 149);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 34);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 93);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 141);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 44);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 73);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 52);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'S', 192);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 14);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 170);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 62);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 79);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 123);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'S', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'M', 142);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 208);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'S', 173);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 213);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 163);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 40);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 12);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'S', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 6);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 166);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 26);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'S', 84);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 81);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 73);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 9);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 15);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 109);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 16);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'M', 186);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 42);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 44);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 170);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'S', 94);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'M', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'M', 107);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 50);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 204);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 196);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'S', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'M', 140);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 84);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 163);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 6);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 24);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'M', 60);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 54);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 9);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 24);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'M', 160);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 10);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 145);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 152);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 56);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 173);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 9);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 170);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'M', 174);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 166);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 51);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'S', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 154);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 19);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'S', 176);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 82);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 9);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 181);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 165);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'M', 85);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 18);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 119);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 109);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'S', 136);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 39);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 37);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'S', 19);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 189);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 181);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 155);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 21);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 153);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'M', 133);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'S', 60);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 8);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'S', 181);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 85);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 92);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 185);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'S', 18);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 45);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 6);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 14);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'S', 128);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'M', 53);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'S', 51);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 55);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 170);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'S', 101);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 18);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 30);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 195);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'S', 99);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 164);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'S', 134);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 4);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 65);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'M', 77);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 43);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'M', 58);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 10);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 159);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 143);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 121);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'M', 145);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 6);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'S', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 56);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 34);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 51);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 203);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'S', 193);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 11);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 53);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 209);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 207);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 74);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 165);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'S', 115);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 107);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'M', 197);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 110);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 26);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 82);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 70);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 3);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'S', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 79);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 169);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 108);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 92);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 81);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'M', 172);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 67);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 41);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 88);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 1);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'S', 76);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 189);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 111);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 109);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 107);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 29);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 111);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 190);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'S', 139);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 147);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'S', 59);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 191);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 33);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'S', 166);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 73);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 31);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'S', 45);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 61);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 164);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 45);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 38);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 8);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'S', 49);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'M', 204);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'S', 155);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 10);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 19);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'M', 110);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'S', 32);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'S', 173);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 106);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 117);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 30);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'M', 200);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 181);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 70);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 42);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 19);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 107);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 15);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 211);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 203);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'S', 40);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 163);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'S', 14);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 137);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 138);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 107);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'M', 2);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 61);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 171);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 164);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 181);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 46);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 37);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 79);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 183);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 213);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 191);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 41);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 0);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 68);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'S', 71);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 108);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'M', 124);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 202);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 163);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 33);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 198);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'S', 213);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'M', 62);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 185);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 167);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 16);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 92);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 27);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 143);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 88);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 4);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 59);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'S', 10);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 176);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 88);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'M', 150);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 126);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 94);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 142);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 101);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'M', 214);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 1);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 166);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 149);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 153);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 72);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 35);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 164);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'M', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'M', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 56);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'M', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 43);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 206);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 176);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'S', 84);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 32);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 186);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 164);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 51);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 155);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 59);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'S', 162);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 152);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 116);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 211);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'M', 121);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'S', 81);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 187);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 103);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 192);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'M', 48);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 199);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 191);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 3);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 108);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 33);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 5);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 98);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 141);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 166);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 28);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 38);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'S', 151);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 64);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 162);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 93);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 108);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 149);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 135);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'M', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 133);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 10);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 37);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'M', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 144);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 162);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'M', 85);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 87);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 59);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 28);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 73);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 156);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 164);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'S', 131);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 15);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'M', 174);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'S', 173);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'M', 170);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 9);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 70);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 204);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 48);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'S', 45);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'S', 188);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'S', 106);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 93);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 205);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'M', 65);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 163);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 57);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 133);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 44);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 97);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'M', 103);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 171);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'M', 213);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Green', 'M', 42);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 27);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 38);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 120);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 121);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 92);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 84);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'M', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 8);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 180);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'S', 29);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'S', 24);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 132);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'M', 145);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 143);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'S', 193);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 59);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'S', 183);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'M', 142);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 77);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 188);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 187);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 91);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'M', 120);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'M', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'M', 18);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'M', 187);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 168);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'S', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 23);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 106);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 11);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 112);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 35);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 202);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 99);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'M', 82);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'M', 159);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 42);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 57);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'S', 116);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 62);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 137);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'S', 143);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 213);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'M', 0);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'S', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'S', 58);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 66);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 84);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'M', 141);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'M', 86);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'M', 133);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 27);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'M', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 154);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'M', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 0);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 54);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 15);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'M', 157);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'M', 120);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 194);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 116);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 176);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 120);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 11);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'M', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 176);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 206);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'S', 13);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 175);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'S', 202);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'M', 111);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 136);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 90);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 202);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 100);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'M', 133);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 179);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'M', 200);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 206);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'S', 76);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'S', 4);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 201);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 135);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 97);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 35);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Mauv', 'S', 69);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'M', 50);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 209);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 204);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'M', 156);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 83);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 100);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 189);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 57);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Teal', 'S', 196);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'M', 20);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Maroon', 'M', 79);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 30);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Crimson', 'M', 11);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 5);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'M', 81);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'M', 203);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'S', 24);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 40);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 182);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 169);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Blue', 'S', 209);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'S', 177);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 69);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 39);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'S', 100);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Yellow', 'M', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'S', 148);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'S', 26);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Indigo', 'M', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 172);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 148);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Green', 'S', 56);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 138);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 131);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Yellow', 'S', 27);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 140);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'S', 167);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 211);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 90);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'S', 174);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 49);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Puce', 'S', 134);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 52);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Teal', 'M', 143);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Turquoise', 'S', 183);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 173);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'M', 72);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 169);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 81);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 78);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'S', 93);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'S', 140);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 22);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'M', 209);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'M', 175);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'M', 135);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Puce', 'M', 170);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 206);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Aquamarine', 'S', 80);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 189);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 145);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 71);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'M', 202);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 65);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'M', 49);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Turquoise', 'S', 95);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'S', 143);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 123);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 110);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 165);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 53);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 153);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Violet', 'S', 84);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 146);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 61);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'S', 108);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'M', 175);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'S', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Orange', 'M', 82);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 23);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'M', 174);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 43);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'S', 22);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'M', 22);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 54);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Puce', 'S', 39);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 0);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 56);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'M', 73);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Khaki', 'S', 165);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 176);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 52);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Red', 'M', 44);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 87);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'M', 153);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Orange', 'M', 114);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Fuscia', 'S', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 23);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 54);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Fuscia', 'S', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Red', 'M', 120);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Aquamarine', 'M', 28);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 24);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 36);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Khaki', 'S', 60);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 118);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 111);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'M', 75);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'M', 37);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Goldenrod', 'M', 198);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'M', 150);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'S', 19);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Fuscia', 'S', 55);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'M', 96);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 135);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Blue', 'M', 122);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Indigo', 'M', 70);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 99);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 8);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Maroon', 'S', 17);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 147);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'S', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'M', 115);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Yellow', 'S', 142);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 106);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'S', 148);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Teal', 'M', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Pink', 'S', 110);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Mauv', 'S', 69);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Goldenrod', 'S', 148);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Crimson', 'M', 15);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'M', 127);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Turquoise', 'S', 210);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'S', 65);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Goldenrod', 'S', 102);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Pink', 'M', 63);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'M', 200);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'M', 30);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Mauv', 'S', 186);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Aquamarine', 'S', 135);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'S', 7);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Green', 'M', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Purple', 'S', 178);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Crimson', 'S', 212);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Khaki', 'S', 106);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Orange', 'M', 116);
insert into shirts (article, color, shirt_size, last_worn) values ('polo shirt', 'Purple', 'M', 153);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Indigo', 'S', 105);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Violet', 'S', 136);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Blue', 'M', 105);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Purple', 'S', 189);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Violet', 'S', 76);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 141);
insert into shirts (article, color, shirt_size, last_worn) values ('t-shirt', 'Maroon', 'M', 203);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Red', 'S', 198);
insert into shirts (article, color, shirt_size, last_worn) values ('tank top', 'Pink', 'M', 126);