<?php
//참고: sendmail.mc 에 설정한 SMART_HOST 부분과는 상관이 없다
//swiftmailer library는 외부smtp를 이용하므로 (다음 smtp를 이용함)
require_once '../projects/kall/vendor/autoload.php';

$transport = (new Swift_SmtpTransport('smtp.daum.net', 465, 'ssl'))
->setUsername('terrificmn') // generated by Mailtrap
->setPassword('84mike19DM') // generated by Mailtrap
;

$mailer = new Swift_Mailer($transport);


$message = (new Swift_Message('Wonderful Subject'))
  ->setFrom(['terrificmn@daum.net' => 'KIM'])  //***중요: smtp.daum.net과 보내는 메일 주소및 아이디가 맞아야 보내지는 듯! 
  //->setTo(['terrificmn@daum.net' =>'test'])
  ->setTo(['mildsm@naver.com' =>'test'])
  ->setBody('Here is the message 테스트 네이버 제발 받아라')
  ;

$result = $mailer->send($message);
if (!isset($result)) {
  echo "fail";
} else {
  echo "success";
}
