version: "3.9"
services: 

  ros:
    container_name: ros
    build: 
      context: .  # 현재 디렉토리
      dockerfile: Dockerfile  
    volumes:
      - ./catkin_ws:/root/catkin_ws   # 현재 디렉토리 기분으로 연결
      - ~/.ssh:/root/.ssh  # 홈디렉토리에 있는 .ssh 연결
    ports:
      - "11311:11311"
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
#    command:
#      - roscore  # Dockerfile의 CMD 효과랑 같지만 훨씬 간결하다



# 현재 도커-컴포즈로는 연결이 안되는 듯 jun11 2021
#테스트용
      #  environment:
      #   - DISPLAY=unix$DISPLAY
      #   - QT_X11_NO_MITSHM=1
      #   devices:
      #   - "/dev/dri:/dev/dri"
      #   privileged: true