version: "3.9"
services: 

  ros:
    container_name: ros
    build: 
      context: .  # 현재 디렉토리
      dockerfile: Dockerfile  


#테스트용
      #  environment:
      #   - DISPLAY=unix$DISPLAY
      #   - QT_X11_NO_MITSHM=1
      #   devices:
      #   - "/dev/dri:/dev/dri"
      #   privileged: true